import type { Metadata } from "next";
import "../app/styles/globals.css";
import { NavBar, Footer } from "../../components/componentsindex";

import { NFTMarketplaceProvider } from "../../context/NFTMarketplaceContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NFTMarketplaceProvider>
          <NavBar />
          {children}
          <Footer />
        </NFTMarketplaceProvider>
      </body>
    </html>
  );
}
